### ISSUE TITLE
[Suggestion] Adding a Dynamic Light mod into the pack

### ISSUE THREAD

**Issue by Lyllittle** [AntoineDehan/Prodigium-Reforged#16]
**Is your feature request related to a problem? Please describe.**
I would like to be able to get light when having a torch in off-hand. It works with shaders enabled but I don't have a good enough GPU for it.

**Describe the solution you'd like**
I think adding this mod would resolve the issue for people who don't want to use shaders but still want to have dynamic light. It is a forge port of the well-known LambDynamicLights mod.
https://www.curseforge.com/minecraft/mc-mods/dynamiclights-reforged

**Comment by JaydenLyte** [comment]
I already made a suggestion here: https://github.com/AntoineDehan/Prodigium-Reforged/issues/9

**Comment by Lyllittle** [comment]
Well, my bad I didn't see it I'm closing this issue.
