### ISSUE TITLE
[BUG]Simply Skill missing perk ?

### ISSUE THREAD

**Issue by Paurcinet** [AntoineDehan/Prodigium-Reforged#19]
Hello, i think 4 perk are missing cause i upgraded everything in the main ranger tree and still got 4 points left. And if u know how to unlock the thief tree (used the mod configured and turned it on in the mods option but nop can't use it like magic warrior and necromancer). 
Still love the modpack
THX.

**Comment by AntoineDehan** [comment]
You can see that thief and things like that are not in the pack yet...
For the point no don't worry that's intended, some class a little bit more skill points to unlock :)
